-- MySQL Script generated by MySQL Workbench
-- Mon Sep 10 20:40:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema zpravodaj
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `zpravodaj` ;

-- -----------------------------------------------------
-- Schema zpravodaj
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zpravodaj` DEFAULT CHARACTER SET utf8 ;
USE `zpravodaj` ;

-- -----------------------------------------------------
-- Table `zpravodaj`.`rssChannel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zpravodaj`.`rssChannel` ;

CREATE TABLE IF NOT EXISTS `zpravodaj`.`rssChannel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `file` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

ALTER TABLE rssChannel ADD timeFormat varchar(20) NULL;
ALTER TABLE rssChannel ADD active tinyint DEFAULT 1 NOT NULL;
ALTER TABLE rssChannel ADD readableName varchar(55) NULL;

CREATE TABLE weather
(
    id int PRIMARY KEY AUTO_INCREMENT,
    apiKey varchar(255),
    `update` timestamp DEFAULT current_timestamp,
    file varchar(255)
);
CREATE UNIQUE INDEX weather_id_uindex ON weather (id);
ALTER TABLE weather ADD cityId int NULL;

CREATE TABLE params
(
    id int PRIMARY KEY AUTO_INCREMENT,
    implementationName varchar(255) NOT NULL,
    value varchar(255) NOT NULL
);
CREATE UNIQUE INDEX params_implementationName_uindex ON params (implementationName);

CREATE TABLE twitterChannel
(
    id int PRIMARY KEY AUTO_INCREMENT,
    user_id int,
    screen_name varchar(255),
    description varchar(255),
    name varchar(52),
    count int DEFAULT 5 COMMENT 'Specifies the number of Tweets to try and retrieve, up to a maximum of 200 '
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
